application: socialplus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /public
  static_dir: public
  expiration: '0'

libraries:
- name: pycrypto
  version: "2.6"
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'socialplus.settings'

builtins:
- django_wsgi: on